---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by david.
--- DateTime: 07/06/2026 13:48
---

local AR = AutoRecruit

--- @class DynamicRunner
local DynamicRunner = {}

function DynamicRunner:New()
    local o = {
        nextZoneID = nil,
        currentZoneID = nil,
        zoneIDFailCount = {}
    }
    setmetatable(o, self)
    self.__index = self
    return o
end

function DynamicRunner:Forward()
    self.nextZoneID = nil
end

function DynamicRunner:OnPortSucceeded()
    self.currentZoneID = self.nextZoneID
    self.nextZoneID = nil
end

function DynamicRunner:OnPortFailed()
    if self.nextZoneID then
        self.zoneIDFailCount[self.nextZoneID] = (self.zoneIDFailCount[self.nextZoneID] or 0) + 1
    end
end

function DynamicRunner:Reset()
    self.zoneIDFailCount = {}
end

function DynamicRunner:Stop()
    self.nextZoneID = nil
end

function DynamicRunner:IsFinished()
    return self:GetNextZone() == nil
end

local function getZonePriority(self, zone)
    local guildIndex = AR.GetGuildIndex(AR.GetGuildIDFromName(AR.settings.recruitFor))
    if AR.lastPosted[zone.name] and AR.settings.skipZoneOnCD then
        local cooldown = AR.settings.adCooldown[guildIndex] * 60 - (GetTimeStamp() - AR.lastPosted[zone.name])

        if cooldown > 10 then
            return -1 -- On cooldown
        end
    end

    local failCount = self.zoneIDFailCount[zone.id] or 0
    if zone.house then
        -- No rush to port to a zone with a house in
        return 50 - 10 * failCount
    elseif zone.players then
        -- Prioritise zones with the fewest players in
        return 100 - #zone.players - 10 * failCount
    else
        return -1 -- No player or house to port to
    end
end

function DynamicRunner:GetNextZone()
    if self.nextZoneID then
        return AR.getZoneById(self.nextZoneID)
    end

    local bestZone
    local bestPriority = 0
    for _, zone in ipairs(AR.zones) do
        local p = getZonePriority(self, zone)
        if p > bestPriority then
            bestZone = zone
            bestPriority = p
        end
    end
    if bestZone then
        self.nextZoneID = bestZone.id
        d(zo_strformat("|c6C00FFAuto Port - |cCCFFCCChosen <<1>> (priority: <<2>>)", bestZone.name, bestPriority))
    else
        self.nextZoneID = nil
        d(zo_strformat("|c6C00FFAuto Port - |cCCCCCCNo zones found to port to"))
    end

    if bestZone == nil then
        -- No zone to port to
        self.lastRound = GetTimeStamp()
    end

    return bestZone
end

function DynamicRunner:GetCurrentZone()
    return AR.getZoneById(self.currentZoneID)
end

function DynamicRunner:GetProgress()
    local guildIndex = AR.GetGuildIndex(AR.GetGuildIDFromName(AR.settings.recruitFor))
    local doneCount = 0
    local totalCount = 0
    for _, zone in ipairs(AR.zones) do
        local cooldown = AR.settings.adCooldown[guildIndex] * 60 - (GetTimeStamp() - AR.lastPosted[zone.name])
        if cooldown > 10 then
            doneCount = doneCount + 1
            totalCount = totalCount + 1
        elseif getZonePriority(self, zone) > 0 then
            totalCount = totalCount + 1
        end
    end

    return doneCount, totalCount
end

function DynamicRunner:GetNextRoundDelay()
    return 15 - (GetTimeStamp()-self.lastRound)
end

AR.DynamicRunner = DynamicRunner
