---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by david.
--- DateTime: 07/06/2026 08:43
---

local AR = AutoRecruit

--- @class LoopRunner
local LoopRunner = {}

function LoopRunner:New()
    local o = {
        nextZone = 1,
        lastRound = nil
    }
    setmetatable(o, self)
    self.__index = self
    return o
end

function LoopRunner:Forward()
    self.nextZone = self.nextZone + 1
end

function LoopRunner:OnPortSucceeded()
    self:Forward()
end

function LoopRunner:OnPortFailed()
end

function LoopRunner:Reset()
    self.nextZone = 1
end

function LoopRunner:Stop()
end

function LoopRunner:IsFinished()
    return self.nextZone > #AR.zones
end

function LoopRunner:GetNextZone()
    if self:IsFinished() then
        d("|c6C00FFAuto Port - |cFFFFFFLoop finished")
        return nil
    end

    if not self.lastRound or self.nextZone == 1 then
        self.lastRound = GetTimeStamp()
    end

    local nextZone = AR.zones[self.nextZone]
    local guildIndex = AR.GetGuildIndex(AR.GetGuildIDFromName(AR.settings.recruitFor))

    if AR.lastPosted[nextZone.name] and AR.settings.skipZoneOnCD then
        local cooldown = AR.settings.adCooldown[guildIndex] * 60 - (GetTimeStamp() - AR.lastPosted[nextZone.name])

        if cooldown > 10 then
            d(zo_strformat("|c6C00FFAuto Port - |cCCFFCCSkipping <<1>> (still on cooldown)", nextZone.name))
            self:Forward()
            return self:GetNextZone()
        end
    end

    if not nextZone.players and not (nextZone.house and CanJumpToHouseFromCurrentLocation()) then
        d(zo_strformat("|c6C00FFAuto Port - |cCCCCCCSkipping <<1>> (could not port)", nextZone.name))
        self:Forward()
        return self:GetNextZone()
    end

    return nextZone
end

function LoopRunner:GetCurrentZone()
    return self.nextZone > 1 and AR.zones[self.nextZone-1] or nil
end

function LoopRunner:GetProgress()
    return self.nextZone - 1, #AR.zones
end

function LoopRunner:GetNextRoundDelay()
    return AR.settings.portingTime*60 - (GetTimeStamp()-self.lastRound)
end

AR.LoopRunner = LoopRunner
